### ISSUE TITLE
Publish for Meteor 0.9+

### ISSUE THREAD

**Issue by jwaltz** [davidwoody/Stripe-Easy-for-Meteor#1]
Can't wait to see this officially published, it's exactly what I was looking to implement myself. Let me know if I can assist with development.

**Comment by davidwoody** [comment]
Thanks for the feedback! I am working to publish this soon.

**Comment by garrilla** [comment]
@davidwoody just adding my marker so I can see when you publish

**Comment by davidwoody** [comment]
http://atmospherejs.com/woody/stripe-easy
