### ISSUE TITLE
SSL required?

### ISSUE THREAD

**Issue by tejasmanohar** [davidwoody/Stripe-Easy-for-Meteor#2]
SSL is required for this and authing with Stripe, etc. correct?

**Comment by davidwoody** [comment]
In production, everything should have SSL (IMO). As documented in the readme, you need to set your Stripe keys up in Meteor settings. Just follow the instructions and let me know if you get hung up on anything, or if something doesn't make sense.

**Comment by tejasmanohar** [comment]
Great, so SSL is required though? since stripe requires it for api interaction?

**Comment by davidwoody** [comment]
It uses the front-end stripe.js library under the hood which takes care of sending the card info to stripe and returns a token that is submitted to the server to actually subscribe the user to the specified plan_id. So technically, I believe SSL is not "required", just highly recommended.

**Comment by vectorselector** [comment]
https://stripe.com/docs/api#authentication

"All API requests must be made over HTTPS. Calls made over plain HTTP will fail. You must authenticate for all requests. "

i'm curious as well...do I need to configure ssl on my localhost to interact with stripe (test keys) while developing?

**Comment by davidwoody** [comment]
@vectorselector you don't need to worry about HTTPS when using test keys in development mode on localhost. Just in production.

**Comment by vectorselector** [comment]
thanks!
