### ISSUE TITLE
Exception while invoking method 'stripeEasySubscribe'

### ISSUE THREAD

**Issue by isAlmogK** [davidwoody/Stripe-Easy-for-Meteor#3]
I'm getting the following error 

Exception while invoking method 'stripeEasySubscribe' TypeError: Cannot read property '0' of undefined
    at Meteor.methods.stripeEasySubscribe (packages/woody:stripe-easy/stripe_easy_server.js:25)
    at methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:179)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1594)
    at packages/ddp/livedata_server.js:648
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
    at packages/ddp/livedata_server.js:647
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
    at _.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646)
    at packages/meteorhacks:kadira/lib/hijack/wrap_session.js:46
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)

**Comment by gdiab** [comment]
Same error here.

**Comment by davidwoody** [comment]
I'm looking into it now.

**Comment by isAlmogK** [comment]
Let me know if you need help on my end, you can also view were I have it setup at - https://linklyapp.com/pricing

It's the strip test not live yet

**Comment by davidwoody** [comment]
I believe you need to make sure you have a logged in user before calling `StripeEasy.subscribe`. The error above is being caused by not being able to read the email address associated with the logged in user in the server call. So you can wrap the call in a createUser call... something like this:

```
Accounts.createUser(args, function(error, result) {
if(error){
  console.log(error)
} else { 
   StripeEasy.subscribe(...)
}
});
```

**Comment by isAlmogK** [comment]
I'm not calling StripeEasy.subscribe(...) on the create user method. I just setup the form like you have on the readme file. Am I missing something?

**Comment by isAlmogK** [comment]
This is what I have 

``` javascript
Template.pricing.events({
    'submit form': function (e) {
        e.preventDefault();
        // make sure there is a Meteor.user() or wrap the following inside the Meteor.createUser callback function
        if(Meteor.user()){
            var easy = StripeEasy.submitHelper(e);
            var plan_id = "linkly-awesome-plan"; // set however you want, via Session variable or a part of the form.
            StripeEasy.subscribe(easy, plan_id, function(err, result){
                // if no error, will return the newly created customer object from Stripe
            });
        }
    }
});
```

**Comment by isAlmogK** [comment]
You can only submit the form if your logged in, if your not logged you can't see it

**Comment by davidwoody** [comment]
Got it. Can you paste the `<form>` html markup ?

**Comment by isAlmogK** [comment]
```
{{#if currentUser}}
                    <div class="row">
                        <div class="col-lg-4 col-sm-4 col-md-offset-3">
                            <form>
                                {{> stripeEasyInputs}}
                                <button class="btn btn-white" type="submit">Submit</button>
                            </form>
                        </div>
                        <div class="col-lg-4 col-sm-4">
                            <h2 class="font-thin">$10/mo</h2>
                            <h4 class="font-thin">Cancel or get a refund anytime.</h4>
                        </div>
                    </div>
                    {{else}}
```

**Comment by davidwoody** [comment]
I was guessing there might have been a naming conflict in the form, but it appears that's not the case. Can you `console.log()` the user object inside of the form submit and paste here? The error basically can't read the emails property on the user object.

**Comment by isAlmogK** [comment]
So I'm getting this back for meteor user 
Object {_id: "WqRY4rLECkgty3y6q", email: "almog00@gmail.com", profile: Object}_id: "WqRY4rLECkgty3y6q"email: "almog00@gmail.com"profile: Object__proto__: Object
pricing.js?b71b7863d5bcf464395a9196ffdfaa5223c2a2e8:9

And I'm also getting this error 
Uncaught TypeError: Cannot read property 'public' of undefined stripe_easy_client.js:32

**Comment by davidwoody** [comment]
Ok, so the short answer is the user object needs to have an `emails` array property on it like this:

```
emails: [{address: 'almog00@gmail.com', verified: false}]
```

I'm not sure what Accounts Entry is doing, but normally Accounts creates a user with the above pattern.

The package should throw a smarter error.

**Comment by davidwoody** [comment]
An easy way to do this is to use the `Accounts.onCreateUser(func)` on the server to make sure the user object has the above pattern.

**Comment by isAlmogK** [comment]
I think there is more to it, the email object you saw was what I did on my end. Meteor doesn't expose user email on the client unless you force it to. This is also why it might work on the account create method which is server side. 

Also there is another issue if a user creates an account via email then you have  
emails: [{address: 'almog00@gmail.com', verified: false}]

But if its Facebook login it's services: {facebook: {email: "xxx@gmail.com"}}

**Comment by isAlmogK** [comment]
I already have the Accounts.onCreateUser(func) that's how I'm setting the emails outside the services object and creating the user profile image. The easiest thing would be just to pass the user email address  

 StripeEasy.subscribe(easy, plan_id, email, function(err, result)

**Comment by isAlmogK** [comment]
This way your not dependent on the user object and or any different log ins that might be used

**Comment by davidwoody** [comment]
So `StripeEasy.subscribe()` only tries to read the `emails` property on the server, so it should not be dependent on the publication. But it does need to have the `emails` property with at least one object with an `address` property.

**Comment by davidwoody** [comment]
I'll update the README now so that it's clear.

**Comment by isAlmogK** [comment]
Right that's the issue the pattern is different depending on the user sign up IE email, Facebook, or google.

**Comment by isAlmogK** [comment]
I just tested it out if I create a user using email it's fine but if it's user created either via Facebook or Google login it does not work. 

The way you have it setup is to only support email signups.

**Comment by isAlmogK** [comment]
Actually attached screenshot showing the correct  emails array property like this:

``` javascript
emails: [{address: 'almog00@gmail.com', verified: false}]
```

But still not working 
![screen shot 2014-10-17 at 5 27 05 pm](https://cloud.githubusercontent.com/assets/169507/4680284/fca2f2d2-5609-11e4-8a7b-bbadf9d05c80.png)

**Comment by davidwoody** [comment]
Make sure you startup meteor with your settings file `meteor --settings path/to/settings.json` ...it needs to have `Meteor.settings.public.Stripe.publicKey`

**Comment by isAlmogK** [comment]
Yes I forgot about that when running from localhost, I did that but now I'm getting the following error. And this is still an issue the package only works with email signup not social login are you going to change it to support social logins?  

I20141017-17:37:48.455(3)? Exception while invoking method 'stripeEasySubscribe' TypeError: Cannot read property 'customers' of undefined
I20141017-17:37:48.457(3)?     at Meteor.methods.stripeEasySubscribe (packages/woody:stripe-easy/stripe_easy_server.js:43)
I20141017-17:37:48.458(3)?     at methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:179)
I20141017-17:37:48.458(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1594)
I20141017-17:37:48.459(3)?     at packages/ddp/livedata_server.js:648
I20141017-17:37:48.459(3)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20141017-17:37:48.459(3)?     at packages/ddp/livedata_server.js:647
I20141017-17:37:48.459(3)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20141017-17:37:48.460(3)?     at _.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646)
I20141017-17:37:48.460(3)?     at packages/ddp/livedata_server.js:546

**Comment by davidwoody** [comment]
You should get a warning in your terminal if Stripe is undefined. This is Stripe's node package... the thing you need to make sure is right is your secret key.

```
// if there is not a secret key set
if(!Meteor.settings || !Meteor.settings.Stripe || !Meteor.settings.Stripe.secretKey){
  console.warn("Stripe secret key is not set in Meteor.settings");
} else {
  var Stripe = Npm.require('stripe')(Meteor.settings.Stripe.secretKey);
}


// TEST WHETHER STRIPE IS DEFINED OR NOT
if(typeof Stripe === "undefined"){
  console.warn("Stripe is not defined");
}
```

Are you getting the warning?

**Comment by isAlmogK** [comment]
No not getting it and my settings JSON 

``` javascript
{
    "public":
        {
            "intercom" :
            {
                "id": "6l93udf"
            },
            "mixpanel" :
            {
                "token": "7a2e24e33025304e0e7dc99724505909"
            },
            "ga" :
            {
                "id" : "UA-48125988-1"
            },
            "Stripe" :
            {
                "publicKey" : "pk_test_oYqHbhmgLabrsePwV1Bn4LhF"
            }
        },

    "intercom":
    {
        "secret" : "mykey"

    },
    "Strip":
    {
        "secretKey" : "mykey"

    }

}
```

**Comment by davidwoody** [comment]
You are missing an `e` in `Meteor.settings.Stripe`

**Comment by isAlmogK** [comment]
ohh didn't even notice that. Everything works now I got back message: 'Your card was declined. Your request was in test mode, but used a non test card. For a list of valid test cards, visit: https://stripe.com/docs/testing.',

But what about the email issue with social logins

**Comment by davidwoody** [comment]
Awesome! 

I'll have to think of the best way to approach that. At the end of the day there needs to be a standard way to define emails on user objects and I think the `emails: [{address: "email@email.com", verified: bool}]` is the best way (because users can have multiple addresses). But I'll think about adding a way to check for other emails if it makes sense. For now though, use `Accounts.onCreateUser(func)` to make sure all users have an email address properly defined.

**Comment by isAlmogK** [comment]
All the users already have an email address defined properly It makes no sense for me to create another object emails: [{address: "email@email.com", verified: bool}] 

You end up creating different objects for the same data, when happens when you a user updates their social email, ect.. It's to ease to run into conflicts or a number of other issues. 

Also when the user has an email not to mention there is no point to verified: bool as there is no verification with social logins.  

What your suggesting is a bad workaround. The best thing to do is pass the email address to the StripeEasy.subscribe() 

Thanks for the help I well look into testing out a different package that supports social login.

**Comment by isAlmogK** [comment]
I have a quick fix let me know what you think

instead of having the following in stripe_easy_server.js

``` javascript
var user = Meteor.users.findOne({_id: this.userId});
var email = user.emails[0].address;
```

have the following (I'm already doing this for the user image)

``` javascript
if (user.services.facebook != undefined) {
       var  email = user.services.facebook.email;
}

if (user.services.google != undefined) {
       var  email = user.services.google.email;
}

if (user.services.password != undefined) {
       var  email = user.emails[0].address;
}
```

I can update the JS file and send you.

**Comment by isAlmogK** [comment]
I already created a merge request 
https://github.com/davidwoody/Stripe-Easy-for-Meteor/pull/4

**Comment by davidwoody** [comment]
Cool, merged... I'll publish a new version of the package sometime this afternoon to include the update.

**Comment by isAlmogK** [comment]
great, can you update the comment so I can know when to update. 

Thanks for the great support, it's a great package very simple and easy to use.

**Comment by davidwoody** [comment]
@almogdesign Just published a new version of the package. You should be able to run `meteor update` and get the changes. I added some better error messages in case a similar issue happens. Let me know if you run into any other issues. Thanks for making the package better and feel free to close this issue after you get it running.

**Comment by isAlmogK** [comment]
thanks
