### ISSUE TITLE
Updating User object upon sucessful subscription

### ISSUE THREAD

**Issue by centinel3** [davidwoody/Stripe-Easy-for-Meteor#7]
Good evening,

I am really excited about finding your package! I have implemented this on my meteor project, and have payments pushing up to the Stripe UI (in test mode) already. My questions are below.

Questions:
1. Does the "StripeEasy.subscribe(easy, plan_id, function(err, result){}" need to be on the server?
1. What is returned in the stripe.subscription property? Is there any way to know if a payment has not gone through after a few successful payments? I'm looking to see how to listen to subscription cancellations, or payments that were working, but have stopped for some reason after a few months so that I can notify the user/restrict access if their subscription isn't up to date.
2. After successful subscription, I don't see the user properties being set (stripe.customerId, stripe.subscription). I'm publishing the user data with specific fields (see my code below) and added the properties as you stated in the description. I also have implemented some code to stop users from being able to modify their user profile from the client console. I commented that out (see below code) opened up the publish to include all fields and have not seen the stripe properties. Any help would be appreciated. Let me know if there is anything else I can do, and thank you again! -Chris

// Publish code (file on the server):
Meteor.publish("accountOwnerData", function () {
  return UsersCollection.find({_id: this.userId}, {fields: {
    '_id': 1,
    'roles': 1,
    'profile.companyId': 1,
    'profile.firstName': 1,
    'profile.lastName': 1,
    'profile.owner': 1,
    'profile.freeTrialEndDate': 1,
    'stripe.customerId': 1,
    'stripe.subscription': 1,
    'emails': 1
  }});
});

// Restrict user profile editing on the client (file on the server):
Meteor.users.deny({
  update: function() {
    return true;
  }
});

**Comment by davidwoody** [comment]
Sorry for the delayed response. I've been on development deadline the past few months.
1. `StripeEasy.subscribe()` should be called client side.
2. To monitor the subscription you need to setup [webhooks](https://stripe.com/docs/webhooks) which is outside the scope of this package.
3. You need to make sure there is `Meteor.user()` before calling `StripeEasy.subscribe()` and the package should take care of the rest.

**Comment by centinel3** [comment]
Thanks for the response David. I ended up going with a native implementation using the Stripe API. -Chris
